### ISSUE TITLE
incompatible encoding regexp match error

### ISSUE THREAD

**Issue by adamcaudill** [digininja/pipal#5] opened 2013-04-21 01:20 UTC
While running pipal against the passwords included in the newseasims.com dump, I ran into an error:

```
$ ./pipal.rb -o 2013.04.20-newseasims_com-pipal 2013.04.20-newseasims_com-pwd 
Generating stats, hit CTRL-C to finish early and dump stats on words already processed.
Please wait...
Something went wrong, please report it to robin@digininja.org along with these messages:

incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string)

Encoding::CompatibilityError

Backtrace:
./pipal.rb:401:in `=~'
./pipal.rb:401:in `block (3 levels) in <main>'
./pipal.rb:331:in `each_line'
./pipal.rb:331:in `block (2 levels) in <main>'
./pipal.rb:329:in `catch'
./pipal.rb:329:in `block in <main>'
/Users/adamcaudill/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/benchmark.rb:281:in `measure'
./pipal.rb:45:in `<main>'
```

I was able to correct the error by changing line pipal.rb:340 from 

```
line.force_encoding("ASCII-8BIT")
```
to:
```
line.force_encoding("UTF-8")
```

Running on OSX:

```
$ ruby -v
ruby 2.0.0p0 (2013-02-24 revision 39474) [x86_64-darwin12.2.1]
```

Not sure if it's because I'm running Ruby 2, or something about my setup, I know the ASCII vs UTF8 issue with Ruby can be a nightmare to get right.

**Comment by digininja** [comment] 2015-12-22 22:42
Couldn't reproduce so closing

**Closed by digininja** 2015-12-22 22:42 UTC
